kind: BuildConfig
apiVersion: v1
metadata:
  name: java-pipeline
  labels:
    app: java-pipeline
spec:
  source:
    git:
      ref: "master"
      uri: "https://github.com/galaxy78-openshift-pipeline/java1-app.git"
    type: Git
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfilePath: jenkins/jenkinsfile 
