kind: BuildConfig
apiVersion: v1
metadata:
  name: nodeapp-pipeline
  labels:
    app: nodeapp-pipeline
spec:
  source:
    git:
      ref: "custom-pipeline"
      uri: "https://github.com/galaxy78-openshift-pipeline/nodejs1-app.git"
    type: Git
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfilePath: jenkins/jenkinsfile 
